name: recipe_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-279.3.beta <4.0.0'

dependencies:
  convex_bottom_bar: ^3.2.0
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  image_picker: ^1.0.8
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
flutter:
  uses-material-design: true
  assets: 
    - assets/
