// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB5cMxI-uFOUl7ORrx528RpBR3p8XzzD8',
    appId: '1:442194889010:web:9706d5b058f59340136f2b',
    messagingSenderId: '442194889010',
    projectId: 'recipe-app-5a80e',
    authDomain: 'recipe-app-5a80e.firebaseapp.com',
    storageBucket: 'recipe-app-5a80e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE1KCch_TySYgIpRjqbT6KkrRkMEFwpHc',
    appId: '1:442194889010:android:66ed396e4f46bf76136f2b',
    messagingSenderId: '442194889010',
    projectId: 'recipe-app-5a80e',
    storageBucket: 'recipe-app-5a80e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwAjzp693tx10PVyiaLCjfJXfgCBTOrd4',
    appId: '1:442194889010:ios:44a4bd2ff1560863136f2b',
    messagingSenderId: '442194889010',
    projectId: 'recipe-app-5a80e',
    storageBucket: 'recipe-app-5a80e.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwAjzp693tx10PVyiaLCjfJXfgCBTOrd4',
    appId: '1:442194889010:ios:44a4bd2ff1560863136f2b',
    messagingSenderId: '442194889010',
    projectId: 'recipe-app-5a80e',
    storageBucket: 'recipe-app-5a80e.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB5cMxI-uFOUl7ORrx528RpBR3p8XzzD8',
    appId: '1:442194889010:web:cf5f7e873b1ab574136f2b',
    messagingSenderId: '442194889010',
    projectId: 'recipe-app-5a80e',
    authDomain: 'recipe-app-5a80e.firebaseapp.com',
    storageBucket: 'recipe-app-5a80e.appspot.com',
  );
}
